spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect  # H2 데이터베이스에 맞는 방언 설정
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace